#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen3_vl/modular_qwen3_vl.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen3_vl.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen Team and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from dataclasses import dataclass, field, asdict
from typing import Any, Callable, Optional, Union, List

import torch
import torch.nn as nn
import torch.nn.functional as F

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub
from transformers.masking_utils import create_causal_mask
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import GradientCheckpointingLayer
from transformers.modeling_outputs import BaseModelOutputWithPast, ModelOutput
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, is_torchdynamo_compiling
from transformers.utils.deprecation import deprecate_kwarg
from transformers.utils.generic import check_model_inputs
from .configuration_deltav import DeltaVConfig, Qwen3VLTextConfig, Qwen3VLVisionConfig

import math

from .backbone_deltav import (
    Qwen3VLVisionMLP,
    Qwen3VLVisionPatchEmbed,
    Qwen3VLVisionRotaryEmbedding,
    Qwen3VLVisionPatchMerger,
    rotate_half,
    apply_rotary_pos_emb_vision,
    repeat_kv,
    eager_attention_forward,
    Qwen3VLVisionAttention,
    Qwen3VLVisionBlock,
    Qwen3VLTextRotaryEmbedding,
    Qwen3VLTextRMSNorm,
    apply_rotary_pos_emb,
    Qwen3VLTextAttention,
    Qwen3VLTextMLP,
    Qwen3VLTextDecoderLayer,
    Qwen3VLModelOutputWithPast,
    Qwen3VLPreTrainedModel,
    Qwen3VLVisionBackbone,
)
from deltav.tsim_tok.modeling_tsim_tok import TSIMTok, TSIMTokExtraCfg, VQCfg

from typing import Optional, Dict, Any

IMAGE_VOCAB_SIZE = 16384
IMAGE_EOS_ID = IMAGE_VOCAB_SIZE
IMAGE_VOCAB_SIZE_WITH_EOS = IMAGE_VOCAB_SIZE + 1





@auto_docstring(
    custom_intro=(
        "Text part of Qwen3VL, "
        "not a pure text-only model, as DeepStack integrates visual features into the early hidden states."
    )
)
class Qwen3VLTextModel(Qwen3VLPreTrainedModel):
    config: Qwen3VLTextConfig
    _no_split_modules = ["Qwen3VLTextDecoderLayer"]

    def __init__(self, config: Qwen3VLTextConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size
        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [Qwen3VLTextDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = Qwen3VLTextRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = Qwen3VLTextRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        # args for deepstack
        visual_pos_masks: Optional[torch.Tensor] = None,
        deepstack_visual_embeds: Optional[list[torch.Tensor]] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Union[tuple, BaseModelOutputWithPast]:
        r"""
        visual_pos_masks (`torch.Tensor` of shape `(batch_size, seqlen)`, *optional*):
            The mask of the visual positions.
        deepstack_visual_embeds (`list[torch.Tensor]`, *optional*):
            The deepstack visual embeddings. The shape is (num_layers, visual_seqlen, embed_dim).
            The feature is extracted from the different visual encoder layers, and fed to the decoder
            hidden states. It's from the paper DeepStack(https://arxiv.org/abs/2406.04334).
        """
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        # torch.jit.trace() doesn't support cache objects in the output
        if use_cache and past_key_values is None and not torch.jit.is_tracing():
            past_key_values = DynamicCache(config=self.config)

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        # the hard coded `3` is for temporal, height and width.
        if position_ids is None:
            position_ids = cache_position.view(1, 1, -1).expand(3, inputs_embeds.shape[0], -1)
        elif position_ids.ndim == 2:
            position_ids = position_ids[None, ...].expand(3, position_ids.shape[0], -1)

        if position_ids.ndim == 3 and position_ids.shape[0] == 4:
            text_position_ids = position_ids[0]
            position_ids = position_ids[1:]
        else:
            text_position_ids = position_ids[0]

        # The original Qwen3VL mapped the attention mask through a no-op pass-through
        # (trainer.py -> train.py return_mask), so create_causal_mask is intentionally
        # not called here; the attention_mask is forwarded to the decoder layers as-is.

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # decoder layers
        for layer_idx, decoder_layer in enumerate(self.layers):
            layer_outputs = decoder_layer(
                hidden_states,
                attention_mask=attention_mask,
                position_ids=text_position_ids,
                past_key_values=past_key_values,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )
            hidden_states = layer_outputs

            # add visual features to the hidden states of first several layers
            if deepstack_visual_embeds is not None and layer_idx in range(len(deepstack_visual_embeds)):
                hidden_states = self._deepstack_process(
                    hidden_states,
                    visual_pos_masks,
                    deepstack_visual_embeds[layer_idx],
                )

        hidden_states = self.norm(hidden_states)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
        )

    def _deepstack_process(
        self, hidden_states: torch.Tensor, visual_pos_masks: torch.Tensor, visual_embeds: torch.Tensor
    ):
        visual_pos_masks = visual_pos_masks.to(hidden_states.device)
        visual_embeds = visual_embeds.to(hidden_states.device, hidden_states.dtype)
        local_this = hidden_states[visual_pos_masks, :].clone() + visual_embeds
        hidden_states[visual_pos_masks, :] = local_this
        return hidden_states


class RMSNorm(torch.nn.Module):
    def __init__(self, dim: int, eps: float = 1e-5):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def _norm(self, x):
        return x * torch.rsqrt(torch.mean(x * x, dim=-1, keepdim=True) + self.eps)

    def forward(self, x):
        output = self._norm(x.float()).type_as(x)
        return output * self.weight


class vision_head(torch.nn.Module):
    def __init__(self, hidden_size: int = 2048, vocab_size_with_eos: int = IMAGE_VOCAB_SIZE_WITH_EOS):
        super().__init__()
        self.output_mlp_projector = torch.nn.Linear(
            hidden_size, hidden_size
        )
        self.vision_activation = torch.nn.GELU()
        self.vision_head = torch.nn.Linear(hidden_size, vocab_size_with_eos)

    def forward(self, x):
        x = self.output_mlp_projector(x)
        x = self.vision_activation(x)
        x = self.vision_head(x)
        return x


class GenMlpProjector(nn.Module):
    def __init__(self, input_dim, n_embed):
        super().__init__()
        mlp_depth = 2
        modules = [nn.Linear(input_dim, n_embed)]
        for _ in range(1, mlp_depth):
            modules.append(nn.GELU())
            modules.append(nn.Linear(n_embed, n_embed))
        modules = nn.Sequential(*modules)
        self.layers = modules

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.layers(x)


@auto_docstring
class DeltaVModel(Qwen3VLPreTrainedModel):
    base_model_prefix = ""
    _checkpoint_conversion_mapping = {}
    # Reference: fix gemma3 grad acc #37208
    accepts_loss_kwargs = False
    config: DeltaVConfig
    _no_split_modules = ["Qwen3VLTextDecoderLayer", "Qwen3VLVisionBlock"]

    def __init__(self, config, extra_cfg: Optional[TSIMTokExtraCfg] = None):
        super().__init__(config)
        self.vision_extra_cfg = extra_cfg
        self.visual = TSIMTok._from_config(config.vision_config, extra_cfg=extra_cfg)
        self.merger = Qwen3VLVisionPatchMerger(
            config=config.vision_config,
            use_postshuffle_norm=False,
        )
        self.deepstack_merger_list = nn.ModuleList(
            [
                Qwen3VLVisionPatchMerger(
                    config=config.vision_config,
                    use_postshuffle_norm=True,
                )
                for _ in range(len(config.vision_config.deepstack_visual_indexes))
            ]
        )
        self.language_model = Qwen3VLTextModel._from_config(config.text_config)
        self.rope_deltas = None  # cache rope_deltas here

        # Visual-token vocabulary / embedding dims are derived from config instead of
        # being hardcoded. Defaults reproduce the released checkpoint exactly:
        # codebook_size=16384 -> eos_id=16384, slot embed dim=12, text hidden=2048.
        _vq = extra_cfg.vq_cfg if extra_cfg is not None else VQCfg()
        image_vocab_size = _vq.codebook_size
        image_vocab_size_with_eos = image_vocab_size + 1
        slot_embed_dim = _vq.codebook_slots_embed_dim
        hidden_size = config.text_config.hidden_size

        self.tok_embeddings = nn.Embedding(image_vocab_size_with_eos, slot_embed_dim)
        self.image_eos_id = image_vocab_size  # EOS id == codebook_size (kept attr name)
        self.gen_projector = GenMlpProjector(slot_embed_dim, hidden_size)
        self.norm = RMSNorm(hidden_size, eps=1e-05)  # follows the VFM pipeline
        self.vision_head = vision_head(hidden_size=hidden_size, vocab_size_with_eos=image_vocab_size_with_eos)  # head modeled after Janus-Pro
        self.lm_head = nn.Linear(config.text_config.hidden_size, config.text_config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.language_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.language_model.set_input_embeddings(value)

    def set_decoder(self, decoder):
        self.language_model = decoder

    def get_decoder(self):
        return self.language_model

    def get_rope_index(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        image_grid_thw: Optional[torch.LongTensor] = None,
        video_grid_thw: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Different from the original implementation, Qwen3VL use timestamps rather than absolute time position ids."""

        # Since we use timestamps to seperate videos, like <t1> <vision_start> <frame1> <vision_end> <t2> <vision_start> <frame2> <vision_end>, the video_grid_thw should also be split
        if video_grid_thw is not None:
            video_grid_thw = torch.repeat_interleave(video_grid_thw, video_grid_thw[:, 0], dim=0)
            video_grid_thw[:, 0] = 1

        spatial_merge_size = self.config.vision_config.spatial_merge_size
        image_token_id = self.config.image_token_id
        video_token_id = self.config.video_token_id
        vision_start_token_id = self.config.vision_start_token_id
        mrope_position_deltas = []
        if input_ids is not None and (image_grid_thw is not None or video_grid_thw is not None):
            total_input_ids = input_ids
            if attention_mask is None:
                attention_mask = torch.ones_like(total_input_ids)
            position_ids = torch.ones(
                3,
                input_ids.shape[0],
                input_ids.shape[1],
                dtype=input_ids.dtype,
                device=input_ids.device,
            )
            image_index, video_index = 0, 0
            attention_mask = attention_mask.to(total_input_ids.device)
            for i, input_ids in enumerate(total_input_ids):
                input_ids = input_ids[attention_mask[i] == 1]
                image_nums, video_nums = 0, 0
                vision_start_indices = torch.argwhere(input_ids == vision_start_token_id).squeeze(1)
                vision_tokens = input_ids[vision_start_indices + 1]
                image_nums = (vision_tokens == image_token_id).sum()
                video_nums = (vision_tokens == video_token_id).sum()
                input_tokens = input_ids.tolist()
                llm_pos_ids_list: list = []
                st = 0
                remain_images, remain_videos = image_nums, video_nums
                for _ in range(image_nums + video_nums):
                    if image_token_id in input_tokens and remain_images > 0:
                        ed_image = input_tokens.index(image_token_id, st)
                    else:
                        ed_image = len(input_tokens) + 1
                    if video_token_id in input_tokens and remain_videos > 0:
                        ed_video = input_tokens.index(video_token_id, st)
                    else:
                        ed_video = len(input_tokens) + 1
                    if ed_image < ed_video:
                        t, h, w = (
                            image_grid_thw[image_index][0],
                            image_grid_thw[image_index][1],
                            image_grid_thw[image_index][2],
                        )
                        image_index += 1
                        remain_images -= 1
                        ed = ed_image

                    else:
                        t, h, w = (
                            video_grid_thw[video_index][0],
                            video_grid_thw[video_index][1],
                            video_grid_thw[video_index][2],
                        )
                        video_index += 1
                        remain_videos -= 1
                        ed = ed_video
                    llm_grid_t, llm_grid_h, llm_grid_w = (
                        t.item(),
                        h.item() // spatial_merge_size,
                        w.item() // spatial_merge_size,
                    )
                    text_len = ed - st

                    st_idx = llm_pos_ids_list[-1].max() + 1 if len(llm_pos_ids_list) > 0 else 0
                    llm_pos_ids_list.append(torch.arange(text_len).view(1, -1).expand(3, -1) + st_idx)

                    # t_index is always 0 because llm_grid_t is always 1 (we use timestamps to encode the temporal information for videos)
                    t_index = torch.arange(llm_grid_t).view(-1, 1).expand(-1, llm_grid_h * llm_grid_w).flatten()
                    h_index = torch.arange(llm_grid_h).view(1, -1, 1).expand(llm_grid_t, -1, llm_grid_w).flatten()
                    w_index = torch.arange(llm_grid_w).view(1, 1, -1).expand(llm_grid_t, llm_grid_h, -1).flatten()
                    llm_pos_ids_list.append(torch.stack([t_index, h_index, w_index]) + text_len + st_idx)
                    st = ed + llm_grid_t * llm_grid_h * llm_grid_w

                if st < len(input_tokens):
                    st_idx = llm_pos_ids_list[-1].max() + 1 if len(llm_pos_ids_list) > 0 else 0
                    text_len = len(input_tokens) - st
                    llm_pos_ids_list.append(torch.arange(text_len).view(1, -1).expand(3, -1) + st_idx)

                llm_positions = torch.cat(llm_pos_ids_list, dim=1).reshape(3, -1)
                position_ids[..., i, attention_mask[i] == 1] = llm_positions.to(position_ids.device)
                mrope_position_deltas.append(llm_positions.max() + 1 - len(total_input_ids[i]))
            mrope_position_deltas = torch.tensor(mrope_position_deltas, device=input_ids.device).unsqueeze(1)
            return position_ids, mrope_position_deltas
        else:
            if attention_mask is not None:
                position_ids = attention_mask.long().cumsum(-1) - 1
                position_ids.masked_fill_(attention_mask == 0, 1)
                position_ids = position_ids.unsqueeze(0).expand(3, -1, -1).to(attention_mask.device)
                max_position_ids = position_ids.max(0, keepdim=False)[0].max(-1, keepdim=True)[0]
                mrope_position_deltas = max_position_ids + 1 - attention_mask.shape[-1]
            else:
                position_ids = (
                    torch.arange(input_ids.shape[1], device=input_ids.device)
                    .view(1, 1, -1)
                    .expand(3, input_ids.shape[0], -1)
                )
                mrope_position_deltas = torch.zeros(
                    [input_ids.shape[0], 1],
                    device=input_ids.device,
                    dtype=input_ids.dtype,
                )

            return position_ids, mrope_position_deltas

    def get_video_features(
        self, pixel_values_videos: torch.FloatTensor, video_grid_thw: Optional[torch.LongTensor] = None
    ):
        """
        Encodes videos into continuous embeddings that can be forwarded to the language model. The deepstack visual features are also returned.

        Args:
            pixel_values_videos (`torch.FloatTensor` of shape `(batch_size, num_channels, image_size, image_size)`):
                The tensors corresponding to the input videos.
            video_grid_thw (`torch.LongTensor` of shape `(num_videos, 3)`, *optional*):
                The temporal, height and width of feature shape of each video in LLM.
        """
        # Same implementation as for images
        return self.get_image_features(pixel_values_videos, video_grid_thw)

    def get_placeholder_mask(
        self,
        input_ids: torch.LongTensor,
        inputs_embeds: torch.FloatTensor,
        image_features: Optional[torch.FloatTensor] = None,
        video_features: Optional[torch.FloatTensor] = None,
    ):
        """
        Obtains multimodal placeholder mask from `input_ids` or `inputs_embeds`, and checks that the placeholder token count is
        equal to the length of multimodal features. If the lengths are different, an error is raised.
        """
        if input_ids is None:
            special_image_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.image_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_image_mask = special_image_mask.all(-1)
            special_video_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.video_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_video_mask = special_video_mask.all(-1)
        else:
            special_image_mask = input_ids == self.config.image_token_id
            special_video_mask = input_ids == self.config.video_token_id

        n_image_tokens = special_image_mask.sum()
        special_image_mask = special_image_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if image_features is not None and inputs_embeds[special_image_mask].numel() != image_features.numel():
            raise ValueError(
                f"Image features and image tokens do not match: tokens: {n_image_tokens}, features {image_features.shape[0]}"
            )

        n_video_tokens = special_video_mask.sum()
        special_video_mask = special_video_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if video_features is not None and inputs_embeds[special_video_mask].numel() != video_features.numel():
            raise ValueError(
                f"Videos features and video tokens do not match: tokens: {n_video_tokens}, features {video_features.shape[0]}"
            )

        return special_image_mask, special_video_mask

    def generate_image_location(self, output_num, num_input_images):
        num_list = output_num.cpu().tolist()
        location = []
        for num, num_input_image in zip(num_list, num_input_images):
            if num == 0 and num_input_image == 0:
                location.append(None)
                continue
            if num_input_image:
                location.extend([False, False]*num_input_image)
            location.extend([True] * num)  
        return location

    def concat_input_output(self, pixel_values, output_pixel_values, image_grid_thw, output_image_grid_thw, num_input_image, output_image_num, tokens_per_image=256):
        num_input_list = num_input_image.tolist()
        num_output_list = output_image_num.tolist()

        if pixel_values is None:
            return output_pixel_values, output_image_grid_thw

        if output_pixel_values is None:
            return pixel_values, image_grid_thw

        # pointers into the token and image dimensions for input/output streams
        in_ptr_tok = 0
        out_ptr_tok = 0
        in_ptr_img = 0
        out_ptr_img = 0

        merged_pixels = []
        merged_grids = []

        for n_in, n_out in zip(num_input_list, num_output_list):

            # pixel_values
            in_tok = n_in * tokens_per_image
            out_tok = n_out * tokens_per_image

            input_chunk = pixel_values[in_ptr_tok: in_ptr_tok + in_tok]
            output_chunk = output_pixel_values[out_ptr_tok: out_ptr_tok + out_tok]

            in_ptr_tok += in_tok
            out_ptr_tok += out_tok

            merged_pixels.append(torch.cat([input_chunk, output_chunk], dim=0))

            # grid
            input_grid = image_grid_thw[in_ptr_img: in_ptr_img + n_in]
            output_grid = output_image_grid_thw[out_ptr_img: out_ptr_img + n_out]

            in_ptr_img += n_in
            out_ptr_img += n_out

            merged_grids.append(torch.cat([input_grid, output_grid], dim=0))

        # final concatenation
        merged_pixel_values = torch.cat(merged_pixels, dim=0)
        merged_image_grid_thw = torch.cat(merged_grids, dim=0)

        return merged_pixel_values, merged_image_grid_thw


    def split_output_image_tokens(
        self,
        first_image_tokens,
        interleave_image_tokens,
        num_input_image,
        output_image_num,
        inter_tokens_per_image,
        token_per_first_image,
    ):
        num_input_list = num_input_image.tolist()
        num_output_list = output_image_num.tolist()

        output_token_chunks = []
        output_token_counts = []   # supervised length of each output image (including eos)

        first_ptr = 0
        inter_ptr = 0

        def append_one_image_tokens(img_tokens):
            eos = torch.tensor([self.image_eos_id], device=img_tokens.device, dtype=img_tokens.dtype)
            output_token_chunks.append(torch.cat([img_tokens, eos], dim=0))
            output_token_counts.append(img_tokens.shape[0] + 1)

        for i in range(len(num_input_list)):
            n_in = num_input_list[i]
            n_out = num_output_list[i]

            # Case 1: no input image
            if n_in == 0:
                if n_out == 0:
                    continue

                # the first output image comes from first_image_tokens
                img_tokens = first_image_tokens[first_ptr:first_ptr + token_per_first_image]
                append_one_image_tokens(img_tokens)
                first_ptr += token_per_first_image

                # the remaining output images come from interleave_image_tokens
                for _ in range(n_out - 1):
                    cur_len = inter_tokens_per_image[inter_ptr]
                    start = sum(inter_tokens_per_image[:inter_ptr])
                    end = start + cur_len
                    img_tokens = interleave_image_tokens[start:end]
                    append_one_image_tokens(img_tokens)
                    inter_ptr += 1

            # Case 2: has input image
            else:
                # the first entry of first_image_tokens is an input image, skip it
                first_ptr += token_per_first_image

                # skip the remaining input images in interleave
                inter_ptr += (n_in - 1)

                if n_out == 0:
                    continue

                # the next n_out images are all output
                for _ in range(n_out):
                    cur_len = inter_tokens_per_image[inter_ptr]
                    start = sum(inter_tokens_per_image[:inter_ptr])
                    end = start + cur_len
                    img_tokens = interleave_image_tokens[start:end]
                    append_one_image_tokens(img_tokens)
                    inter_ptr += 1

        if len(output_token_chunks) > 0:
            output_tokens = torch.cat(output_token_chunks, dim=0)
        else:
            output_tokens = torch.empty(0, device=first_image_tokens.device, dtype=first_image_tokens.dtype)

        return output_tokens, output_token_counts


    def split_first_and_interleave_vectorized(self, gen_image_tokens: torch.Tensor, seq_image_counts: torch.Tensor, tokens_per_image: int):
       
        device = gen_image_tokens.device

        # reshape to per-image granularity
        total_images = seq_image_counts.sum()
        image_tokens = gen_image_tokens.view(
            total_images, tokens_per_image
        )  # (N_img, T, D)

        # which sequence each image belongs to
        seq_ids = torch.repeat_interleave(
            torch.arange(len(seq_image_counts), device=device),
            seq_image_counts
        )  # (N_img,)

        # index of each image within its sequence
        seq_start = torch.cumsum(seq_image_counts, dim=0) - seq_image_counts
        seq_start = seq_start.repeat_interleave(seq_image_counts)
        image_indices = torch.arange(total_images, device=device)
        image_idx_in_seq = image_indices - seq_start  # (N_img,)

        # masks for the first image vs. the interleaved images in each sequence
        first_mask = image_idx_in_seq == 0
        interleave_mask = image_idx_in_seq > 0

        # gather and flatten
        first_gen_image_tokens = image_tokens[first_mask].reshape(-1)
        interleave_gen_image_tokens = image_tokens[interleave_mask].reshape(-1)

        return first_gen_image_tokens, interleave_gen_image_tokens

    def und_encoder(self, hidden_states, process_hidden_states):
        deepstack_feature_lists = []
        for i, x in enumerate(process_hidden_states):
            deepstack_feature = self.deepstack_merger_list[i](x)
            deepstack_feature_lists.append(deepstack_feature)
        
        hidden_states = self.merger(hidden_states)
        return hidden_states, deepstack_feature_lists


    @auto_docstring
    @check_model_inputs
    def forward(
        self,
        input_ids: torch.LongTensor = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        und_pixel_values: Optional[torch.Tensor] = None,
        pixel_values: Optional[torch.Tensor] = None,
        output_pixel_values: Optional[torch.Tensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        und_image_grid_thw: Optional[torch.LongTensor] = None,
        image_grid_thw: Optional[torch.LongTensor] = None,
        output_image_grid_thw: Optional[torch.LongTensor] = None,
        video_grid_thw: Optional[torch.LongTensor] = None,
        cache_position: Optional[torch.LongTensor] = None,
        output_image_num: Optional[torch.Tensor] = None,
        num_input_image: Optional[torch.Tensor] = None,
        num_tokens: Optional[torch.Tensor] = None,
        incremental_encoding: bool = True,
        **kwargs: Unpack[TransformersKwargs],
    ) -> Union[tuple, Qwen3VLModelOutputWithPast]:
        r"""
        image_grid_thw (`torch.LongTensor` of shape `(num_images, 3)`, *optional*):
            The temporal, height and width of feature shape of each image in LLM.
        video_grid_thw (`torch.LongTensor` of shape `(num_videos, 3)`, *optional*):
            The temporal, height and width of feature shape of each video in LLM.
        """
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")
        if inputs_embeds is None:
            inputs_embeds = self.get_input_embeddings()(input_ids)  # e.g. torch.Size([1, 460, 2048]); the batch is packed along the second dimension, so bs=4 yields torch.Size([1, 1840, 2048])

        output_image_index = None
        image_mask = None
        video_mask = None
        
        if pixel_values is not None:
            und_input_hidden_states, und_input_process_hidden_states = self.visual.backbone(und_pixel_values, und_image_grid_thw)
            image_embeds, deepstack_image_embeds = self.und_encoder(und_input_hidden_states, und_input_process_hidden_states)
            image_embeds = image_embeds.to(inputs_embeds.device, inputs_embeds.dtype)
            image_mask, _ = self.get_placeholder_mask(  # image positions are True (after the first few leading tokens)
                input_ids, inputs_embeds=inputs_embeds, image_features=image_embeds
            )
            inputs_embeds = inputs_embeds.masked_scatter(image_mask, image_embeds)  # scatter the image embedding features into their positions in inputs_embeds

        if (pixel_values is not None) or (output_pixel_values is not None):
            merged_pixel_values, merged_image_grid_thw = self.concat_input_output(pixel_values, output_pixel_values, image_grid_thw, output_image_grid_thw, num_input_image, output_image_num, 256)  # tokens_per_image to adjust if resolution changes
            hidden_states, process_hidden_states = self.visual.backbone(merged_pixel_values, merged_image_grid_thw)
            if incremental_encoding:
                num_merge_image = (num_input_image + output_image_num)[(num_input_image + output_image_num) != 0]
                first_image_tokens, interleave_image_tokens = self.visual.encode_forward(hidden_states, process_hidden_states, merged_image_grid_thw, num_merge_image, num_tokens)
            else:
                single_image_num = torch.ones(sum(num_input_image + output_image_num), dtype=torch.int64)
                first_image_tokens, interleave_image_tokens = self.visual.encode_forward(hidden_states, process_hidden_states, merged_image_grid_thw, single_image_num, [])
                num_merge_image = (num_input_image + output_image_num)[(num_input_image + output_image_num) != 0]
                first_image_tokens, interleave_image_tokens = self.split_first_and_interleave_vectorized(first_image_tokens, num_merge_image, tokens_per_image=self.vision_extra_cfg.gen_cfg.n_base)


            first_gen_image_embeddings = self.gen_projector(self.tok_embeddings(first_image_tokens))
            interleave_gen_image_embeddings = self.gen_projector(self.tok_embeddings(interleave_image_tokens))
            label_output_image_tokens, output_token_counts = self.split_output_image_tokens(
                first_image_tokens,
                interleave_image_tokens,
                num_input_image,
                output_image_num,
                num_tokens,
                self.vision_extra_cfg.gen_cfg.n_base,
            )
            image_gen_indices = (input_ids == self.config.vision_end_token_id).nonzero()
            image_location = self.generate_image_location(output_image_num, num_input_image)
            output_image_index = []
            false_counter = 0
            seq_counter = 0
            seq_image_counter = [0] * len(output_image_num)

            # pointer initialization
            token_per_first_image = self.vision_extra_cfg.gen_cfg.n_base  # fixed token count for the first image
            first_ptr = 0
            inter_ptr = 0  # points into interleave_gen_image_embeddings

            no_image_data = 0
            for ii in range(len(image_location)):
                if image_location[ii] == None:
                    no_image_data += 1
                    seq_counter += 1
                    continue
                
                ind = image_gen_indices[ii - no_image_data]
                if image_location[ii] is False:
                    false_counter += 1
                    if false_counter % 2 == 0:
                        continue
                    
                # which sequence the current image belongs to
                seq_id = seq_counter
                # which image this is within the sequence (input + output counted together)
                img_idx_in_seq = seq_image_counter[seq_id]

                # select the embedding
                if img_idx_in_seq == 0:
                    image_embed = first_gen_image_embeddings[first_ptr : first_ptr + token_per_first_image]
                    first_ptr += token_per_first_image
                else:
                    num_tokens_current = num_tokens[inter_ptr]  # token count of the current image
                    start = sum(num_tokens[:inter_ptr])
                    end = start + num_tokens_current
                    image_embed = interleave_gen_image_embeddings[start:end]
                    inter_ptr += 1
                image_eos_embed = self.gen_projector(
                    self.tok_embeddings.weight[self.image_eos_id:self.image_eos_id+1]
                ).to(inputs_embeds.device, inputs_embeds.dtype)   # [1, hidden_dim]
                # write
                if image_location[ii] is False:
                    # input image (same logic as the original)
                    offset = ind[1] + 2
                    inputs_embeds[ind[0], offset: offset + image_embed.shape[0], :] = image_embed
                    inputs_embeds[ind[0], offset + image_embed.shape[0], :] = image_eos_embed[0]
                else:
                    # output image
                    offset = ind[1]
                    inputs_embeds[ind[0], offset - image_embed.shape[0]: offset, :] = image_embed
                    # replace the embedding of the <|vision_end|> text token with the image eos embedding
                    inputs_embeds[ind[0], offset, :] = image_eos_embed[0]

                    # note: the supervised span now includes eos, so end is offset + 1
                    output_image_index.append([offset - image_embed.shape[0], offset + 1])

                seq_image_counter[seq_id] += 1
                # whether the current sequence is finished (total of input + output images)
                total_images_in_seq = num_input_image[seq_id] + output_image_num[seq_id]
                if seq_image_counter[seq_id] == total_images_in_seq:
                    seq_counter += 1

        else:
            label_output_image_tokens = torch.empty(
                0,
                self.vision_extra_cfg.gen_cfg.n_base,
                device=inputs_embeds.device,
            )
            output_token_counts = []

        if pixel_values_videos is not None:
            video_embeds, deepstack_video_embeds = self.get_video_features(pixel_values_videos, video_grid_thw)
            video_embeds = torch.cat(video_embeds, dim=0).to(inputs_embeds.device, inputs_embeds.dtype)
            _, video_mask = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, video_features=video_embeds
            )
            inputs_embeds = inputs_embeds.masked_scatter(video_mask, video_embeds)

        visual_pos_masks = None
        deepstack_visual_embeds = None
        if image_mask is not None and video_mask is not None:
            # aggregate visual_pos_masks and deepstack_visual_embeds
            image_mask = image_mask[..., 0]
            video_mask = video_mask[..., 0]
            visual_pos_masks = image_mask | video_mask
            deepstack_visual_embeds = []
            image_mask_joint = image_mask[visual_pos_masks]
            video_mask_joint = video_mask[visual_pos_masks]
            for img_embed, vid_embed in zip(deepstack_image_embeds, deepstack_video_embeds):
                embed_joint = img_embed.new_zeros(visual_pos_masks.sum(), img_embed.shape[-1]).to(img_embed.device)
                embed_joint[image_mask_joint, :] = img_embed
                embed_joint[video_mask_joint, :] = vid_embed
                deepstack_visual_embeds.append(embed_joint)
        elif image_mask is not None:
            image_mask = image_mask[..., 0]  # torch.Size([1, 460, 2048])
            visual_pos_masks = image_mask  # torch.Size([1, 460])
            deepstack_visual_embeds = deepstack_image_embeds
        elif video_mask is not None:
            video_mask = video_mask[..., 0]
            visual_pos_masks = video_mask
            deepstack_visual_embeds = deepstack_video_embeds

        if position_ids is None:  # unused in this path; can be skipped
            attention_mask_tensor = (
                attention_mask if not isinstance(attention_mask, dict) else attention_mask["full_attention"]
            )
            if attention_mask_tensor is not None and attention_mask_tensor.ndim == 4:
                attention_mask_tensor = torch.diagonal(attention_mask_tensor[:, 0], dim1=1, dim2=2)
                # Only apply conversion for floating point tensors (inverted masks)
                if attention_mask_tensor.dtype.is_floating_point:
                    attention_mask_tensor = attention_mask_tensor / torch.finfo(attention_mask_tensor.dtype).min
                    attention_mask_tensor = (1.0 - attention_mask_tensor).int()

            # Calculate RoPE index once per generation in the pre-fill stage only.
            # When compiling, we can't check tensor values thus we check only input length
            # It is safe to assume that `length!=1` means we're in pre-fill because compiled
            # models currently cannot do asssisted decoding
            prefill_compiled_stage = is_torchdynamo_compiling() and (
                (input_ids is not None and input_ids.shape[1] != 1)
                or (inputs_embeds is not None and inputs_embeds.shape[1] != 1)
            )
            prefill_noncompiled_stage = not is_torchdynamo_compiling() and (
                (cache_position is not None and cache_position[0] == 0)
                or (past_key_values is None or past_key_values.get_seq_length() == 0)
            )
            if (prefill_compiled_stage or prefill_noncompiled_stage) or self.rope_deltas is None:
                position_ids, rope_deltas = self.get_rope_index(
                    input_ids,
                    und_image_grid_thw,
                    video_grid_thw,
                    attention_mask=None,
                )
                self.rope_deltas = rope_deltas
            # then use the prev pre-calculated rope-deltas to get the correct position ids
            else:
                batch_size, seq_length, _ = inputs_embeds.shape
                delta = (
                    (cache_position[0] + self.rope_deltas).to(inputs_embeds.device)
                    if cache_position is not None
                    else 0
                )
                position_ids = torch.arange(seq_length, device=inputs_embeds.device)
                position_ids = position_ids.view(1, -1).expand(batch_size, -1)
                if cache_position is not None:  # otherwise `deltas` is an int `0`
                    delta = delta.repeat_interleave(batch_size // delta.shape[0], dim=0)
                position_ids = position_ids.add(delta)
                position_ids = position_ids.unsqueeze(0).expand(3, -1, -1)

        outputs = self.language_model(
            input_ids=None,
            position_ids=position_ids,
            attention_mask=attention_mask,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            cache_position=cache_position,
            visual_pos_masks=visual_pos_masks,
            deepstack_visual_embeds=deepstack_visual_embeds,
            **kwargs,
        )
        
        return Qwen3VLModelOutputWithPast(
            last_hidden_state=outputs.last_hidden_state,
            past_key_values=outputs.past_key_values,
            rope_deltas=self.rope_deltas,
        ), label_output_image_tokens, output_image_index, output_token_counts


__all__ = [
    "DeltaVModel",
]
